name: My Awesome Hack-a-Thon AMP          # Name your Project
description: Does awesome ML!             # Brief description of your project
author: Cloudera Inc.
specification_version: 1.0
prototype_version: 1.0
date: "2022-XX-XX"                        # Enter the submission date

runtimes:
  - editor: Workbench
    kernel: Python 3.9                    # Fill in the Python version used for your AMP
    edition: Standard
    browser-type: chrome
    headless-browsing: no
    dataset-existing: yes

tasks:
  - type: run_session
    name: Install Dependencies
    script: scripts/install_dependencies.py # enter pathname of your install script
    memory: 2
    cpu: 1

  - type: run_session
    name: Preparing data
    script: scripts/train_data.py      # enter pathname of your data download script
    memory: 2
    cpu: 1

  - type: run_session
    name: Train Model
    script: scripts/Numerical_Model.py              # enter the pathname of your model training script
    memory: 4
    cpu: 2

  - type: run_session
    name: Train Model 2
    script: scripts/Image_Regression_Model.py              # enter the pathname of your model training script
    memory: 4
    cpu: 2

  - type: start_application
    short_summary: Launch application
    name: My Vizualation Application      # Name your application
    subdomain: mlapp
    script: app/launch_app.py         # enter the pathname of script that launches your visualization/application
    environment_variables:
      TASK_TYPE: START_APPLICATION
    cpu: 1
    memory: 2